/** Shape of packages/aurora/public/tiles.json, generated by scripts/tiles/make-tiles-json.ts. */
export interface TilesConfig {
  coordinateSpace: string
  tileSize: number
  maxLevel: number
  format: string
  cellSize: number
  originSquare: { x: number; y: number }
  squaresPerPixelAtMax: number
  world: { pixels: { w: number; h: number }; squares: { w: number; h: number } }
  layers: { min: number; max: number; ground: number }
  baseUrl: string
  tileUrlTemplate: string
}

export function tileUrl(
  cfg: TilesConfig,
  layer: number,
  z: number,
  x: number,
  y: number,
  baseOverride?: string,
): string {
  const base = (baseOverride ?? cfg.baseUrl).replace(/\/+$/, '')
  return cfg.tileUrlTemplate
    .replace('{baseUrl}', base)
    .replace('{layer}', String(layer))
    .replace('{z}', String(z))
    .replace('{x}', String(x))
    .replace('{y}', String(y))
}
