/** Shape of packages/aurora/public/tiles.json, generated by scripts/tiles/make-tiles-json.ts. */
export interface TilesConfig {
  coordinateSpace: string
  tileSize: number
  maxLevel: number
  format: string
  cellSize: number
  originSquare: { x: number; y: number }
  squaresPerPixelAtMax: number
  world: { pixels: { w: number; h: number }; squares: { w: number; h: number } }
  layers: { min: number; max: number; ground: number }
  baseUrl: string
  tileUrlTemplate: string
}

export function tileUrl(
  cfg: TilesConfig,
  layer: number,
  z: number,
  x: number,
  y: number,
  baseOverride?: string,
): string {
  const base = (baseOverride ?? cfg.baseUrl).replace(/\/+$/, '')
  return cfg.tileUrlTemplate
    .replace('{baseUrl}', base)
    .replace('{layer}', String(layer))
    .replace('{z}', String(z))
    .replace('{x}', String(x))
    .replace('{y}', String(y))
}

/**
 * zombie_top's own pyramid (T22 Part C): same tile geometry as base_top - same tileSize,
 * maxLevel, format and cellSize - published under a different top-level folder. `tileUrl`
 * above goes through `tileUrlTemplate`, which names `base_top` literally (T11's generator),
 * so this is built directly from the fields that actually vary rather than string-patching
 * that template.
 */
export function zombieTileUrl(
  cfg: TilesConfig,
  layer: number,
  z: number,
  x: number,
  y: number,
  baseOverride?: string,
): string {
  const base = (baseOverride ?? cfg.baseUrl).replace(/\/+$/, '')
  return `${base}/zombie_top/layer${layer}_files/${z}/${x}_${y}.${cfg.format}`
}
