/**
 * T45 Part PUBLISH: a mod map rendered with `dzi_cell_range: all_mod_maps` (Part RENDER)
 * shares the base pyramid's exact geometry, so it is just another tile layer on the same
 * grid rather than its own coordinate system. `id` is the mod map's own folder name under
 * `mod_maps/` (stable, used in the tile URL); `title` is a display name (today, the same
 * string as `id` - see scripts/tiles/make-tiles-json.ts for where this is built);
 * `cellRects` is that map's own populated-cell rectangles, not the base's.
 */
export interface TileOverlay {
  id: string
  title: string
  tileUrlTemplate: string
  cellRects: [number, number, number, number][]
}

/** Shape of packages/aurora/public/tiles.json, generated by scripts/tiles/make-tiles-json.ts. */
export interface TilesConfig {
  coordinateSpace: string
  tileSize: number
  maxLevel: number
  format: string
  cellSize: number
  originSquare: { x: number; y: number }
  squaresPerPixelAtMax: number
  world: { pixels: { w: number; h: number }; squares: { w: number; h: number } }
  layers: { min: number; max: number; ground: number }
  baseUrl: string
  tileUrlTemplate: string
  /**
   * Absent from today's tiles.json (no map mods rendered yet), and MUST stay optional so
   * that file keeps working unchanged: every reader treats a missing/empty `overlays` as
   * "no mod maps", never as an error.
   */
  overlays?: TileOverlay[]
}

export function tileUrl(
  cfg: TilesConfig,
  layer: number,
  z: number,
  x: number,
  y: number,
  baseOverride?: string,
): string {
  const base = (baseOverride ?? cfg.baseUrl).replace(/\/+$/, '')
  return cfg.tileUrlTemplate
    .replace('{baseUrl}', base)
    .replace('{layer}', String(layer))
    .replace('{z}', String(z))
    .replace('{x}', String(x))
    .replace('{y}', String(y))
}

/**
 * T45 Part PUBLISH: a mod-map overlay's own pyramid. Unlike `zombieTileUrl` below, an
 * overlay's `tileUrlTemplate` already names its own id (`{baseUrl}/mod_maps/<id>/base_top/
 * layer{layer}_files/{z}/{x}_{y}.webp`, written once by make-tiles-json.ts), so this
 * resolves the overlay's OWN template rather than `cfg.tileUrlTemplate` - the two are kept
 * as separate small functions (matching `zombieTileUrl`'s own precedent below) rather than
 * folded into one generic helper, so neither reader has to guess which template argument
 * a shared function meant.
 */
export function overlayTileUrl(
  overlay: TileOverlay,
  cfg: TilesConfig,
  layer: number,
  z: number,
  x: number,
  y: number,
  baseOverride?: string,
): string {
  const base = (baseOverride ?? cfg.baseUrl).replace(/\/+$/, '')
  return overlay.tileUrlTemplate
    .replace('{baseUrl}', base)
    .replace('{layer}', String(layer))
    .replace('{z}', String(z))
    .replace('{x}', String(x))
    .replace('{y}', String(y))
}

/**
 * zombie_top's own pyramid (T22 Part C): same tile geometry as base_top - same tileSize,
 * maxLevel, format and cellSize - published under a different top-level folder. `tileUrl`
 * above goes through `tileUrlTemplate`, which names `base_top` literally (T11's generator),
 * so this is built directly from the fields that actually vary rather than string-patching
 * that template.
 */
export function zombieTileUrl(
  cfg: TilesConfig,
  layer: number,
  z: number,
  x: number,
  y: number,
  baseOverride?: string,
): string {
  const base = (baseOverride ?? cfg.baseUrl).replace(/\/+$/, '')
  return `${base}/zombie_top/layer${layer}_files/${z}/${x}_${y}.${cfg.format}`
}
