/**
 * "Made by Dystopian Outcasts": the community's own mods that run on the server.
 *
 * The list itself is data/ourMods.json, generated by scripts/build-our-mods.ts from the
 * Workshop folders. Pure functions only (grouping, name tidying, matching the server's
 * live mod list), so they can be tested without a browser (ourMods.test.ts).
 */

export type ModGroup = 'Outcast' | 'Dystopian' | 'Cosmic' | 'Squirrelly Industries'

export interface OurMod {
  /** The mod id the server lists in Mods=. */
  id: string
  workshopId: string
  name: string
  group: ModGroup
  blurb: string
  /** "derived" when the blurb was written from the mod's files, not its mod.info. */
  blurbSource?: 'derived'
  /** Why the name differs from mod.info, when it does. */
  note?: string
  /** Site path of the poster (webp), or null when the mod has none. */
  poster: string | null
  /** Pixel size of the poster, for the image's width and height attributes. */
  posterWidth?: number
  posterHeight?: number
}

/** The order the groups are shown in. */
export const GROUP_ORDER: ModGroup[] = ['Outcast', 'Dystopian', 'Cosmic', 'Squirrelly Industries']

/**
 * Never shown, whatever the data holds: OutcastAurora is an internal server tool,
 * OutcastLib a shared library with no gameplay, OutcastStowAll is abandoned.
 */
export const NEVER_SHOWN = ['OutcastAurora', 'OutcastLib', 'OutcastStowAll']

/** Cards shown per group before "Show all N". */
export const COLLAPSE_AFTER = 6

export interface ModGroupList {
  group: ModGroup
  mods: OurMod[]
}

/** "DystopianTinkering" as "Dystopian Tinkering". A name that already has spaces is only trimmed. */
export function tidyName(raw: string): string {
  const name = raw.trim()
  if (name.includes(' ')) return name
  return name.replace(/(?<=[a-z])(?=[A-Z])/g, ' ')
}

/** "OutcastLightLoad" as "outcast-light-load", the wiki category id of its guide. */
export function guideSlug(id: string): string {
  return id.replace(/(?<=[a-z])(?=[A-Z])/g, '-').toLowerCase()
}

/** The mods that may be shown: everything but the never-shown ones, compared case-insensitively. */
export function visibleMods(mods: OurMod[]): OurMod[] {
  const hidden = new Set(NEVER_SHOWN.map((id) => id.toLowerCase()))
  return mods.filter((m) => !hidden.has(m.id.toLowerCase()))
}

/** Visible mods in group order; a group with no mods is left out, a mod in an unknown group is not shown. */
export function groupMods(mods: OurMod[]): ModGroupList[] {
  const shown = visibleMods(mods)
  return GROUP_ORDER.map((group) => ({ group, mods: shown.filter((m) => m.group === group) })).filter(
    (g) => g.mods.length > 0,
  )
}

/** The server's live mod ids (settings.Mods) as a lower-case set; a list or a ";"-separated string. */
export function liveModIds(raw: unknown): Set<string> {
  const parts = Array.isArray(raw) ? raw : typeof raw === 'string' ? raw.split(';') : []
  const ids = new Set<string>()
  for (const p of parts) {
    if (typeof p === 'string' && p.trim() !== '') ids.add(p.trim().toLowerCase())
  }
  return ids
}

/** True when the mod is in the live list; ids differ in case between mod.info and the server. */
export function isOnServer(live: Set<string>, id: string): boolean {
  return live.has(id.toLowerCase())
}

export function steamUrl(workshopId: string): string {
  return `https://steamcommunity.com/sharedfiles/filedetails/?id=${workshopId}`
}
