// GENERATED by scripts/build-nav.ts from content/versions.config.json and the
// content/articles tree. Do not edit by hand; edit the config or the content and
// re-run `npx tsx scripts/build-nav.ts`.

export type VersionStatus = 'current' | 'legacy' | 'upcoming'

export interface CategoryInfo {
  id: string
  name: string
  description: string
  icon: string
  articleCount: number
  displayOrder: number
}

export interface SectionInfo {
  id: string
  name: string
  description: string
  icon: string
  displayOrder: number
  categories: CategoryInfo[]
}

export interface VersionInfo {
  id: string
  name: string
  releaseDate: string
  status: VersionStatus
  description: string
  sections: SectionInfo[]
}

export const GAME = 'pz'

export const DEFAULT_VERSION = 'build-41'

export const VERSIONS: VersionInfo[] = [
  {
    id: 'build-41',
    name: 'Build 41',
    releaseDate: '2021-12-20',
    status: 'legacy',
    description: 'The previous stable build. Guides here are kept as written and are not updated for Build 42.',
    sections: [
      {
        id: 'modding',
        name: 'Modding',
        description: 'Learn to create mods for Project Zomboid',
        icon: 'plug',
        displayOrder: 1,
        categories: [
          {
            id: 'fundamentals',
            name: 'Fundamentals',
            description: 'Essential concepts for understanding Project Zomboid modding: architecture, file structure, and syntax basics.',
            icon: 'book',
            displayOrder: 1,
            articleCount: 4,
          },
          {
            id: 'setup',
            name: 'Setup',
            description: 'Set up your development environment for PZ modding: editors, folder structure, and debug tools.',
            icon: 'settings',
            displayOrder: 2,
            articleCount: 4,
          },
          {
            id: 'ai-assisted',
            name: 'AI-Assisted Modding',
            description: 'Use AI tools to accelerate your modding workflow without deep coding knowledge.',
            icon: 'sparkles',
            displayOrder: 3,
            articleCount: 5,
          },
          {
            id: 'lua-api',
            name: 'Lua API',
            description: 'Events, callbacks, and the core Lua scripting interface for Project Zomboid modding.',
            icon: 'scroll',
            displayOrder: 4,
            articleCount: 9,
          },
          {
            id: 'ui-framework',
            name: 'UI Framework',
            description: 'Project Zomboid\'s ISUI component system for building custom interfaces.',
            icon: 'layout',
            displayOrder: 5,
            articleCount: 5,
          },
          {
            id: 'reference',
            name: 'API Reference',
            description: 'Complete reference data for PZ\'s Lua API: events, globals, and script properties.',
            icon: 'database',
            displayOrder: 6,
            articleCount: 6,
          },
          {
            id: 'recipes',
            name: 'Recipes',
            description: 'Create custom crafting recipes for items, weapons, and consumables.',
            icon: 'wrench',
            displayOrder: 7,
            articleCount: 8,
          },
          {
            id: 'items',
            name: 'Items',
            description: 'Define new items with custom properties, textures, and behaviors.',
            icon: 'box',
            displayOrder: 8,
            articleCount: 8,
          },
          {
            id: 'game-mechanics',
            name: 'Game Mechanics',
            description: 'Modify and extend core game systems like injuries, skills, and weather.',
            icon: 'zap',
            displayOrder: 11,
            articleCount: 3,
          },
          {
            id: 'weapon-repair',
            name: 'Weapon Repair',
            description: 'Implement weapon maintenance and repair systems for custom weapons.',
            icon: 'hammer',
            displayOrder: 12,
            articleCount: 7,
          },
          {
            id: 'foraging',
            name: 'Foraging',
            description: 'Add custom foraging definitions and loot tables.',
            icon: 'leaf',
            displayOrder: 13,
            articleCount: 1,
          },
          {
            id: 'tools',
            name: 'Tools',
            description: 'Development tools, debugging techniques, and workflow tips.',
            icon: 'tool',
            displayOrder: 14,
            articleCount: 4,
          },
          {
            id: 'vanilla-reference',
            name: 'Vanilla Reference',
            description: 'Comprehensive reference documentation for all vanilla Project Zomboid items, weapons, recipes, and game data.',
            icon: 'database',
            displayOrder: 15,
            articleCount: 16,
          },
          {
            id: 'engine-analysis',
            name: 'Engine Analysis',
            description: 'How the Java engine behind the Lua API works: decompilation, zombie and vehicle internals, reflection, and performance.',
            icon: 'gear',
            displayOrder: 16,
            articleCount: 18,
          },
        ],
      },
      {
        id: 'mapping',
        name: 'Mapping',
        description: 'Create custom maps with TileZed and WorldEd',
        icon: 'map',
        displayOrder: 2,
        categories: [
          {
            id: 'video-tutorials',
            name: 'Video Tutorials',
            description: 'Complete 29-part video guide series for learning PZ map making from scratch',
            icon: 'video',
            displayOrder: 1,
            articleCount: 1,
          },
        ],
      },
    ],
  },
  {
    id: 'build-42',
    name: 'Build 42',
    releaseDate: '2026-07-29',
    status: 'current',
    description: 'The current stable build (42.20 and later). Modding, mapping, vehicles and the Outcast mods.',
    sections: [],
  },
]

export function getVersion(id: string | undefined): VersionInfo | undefined {
  return VERSIONS.find((v) => v.id === id)
}

export function getSection(versionId: string | undefined, sectionId: string | undefined): SectionInfo | undefined {
  return getVersion(versionId)?.sections.find((s) => s.id === sectionId)
}
