// GENERATED by scripts/build-nav.ts from content/versions.config.json and the
// content/articles tree. Do not edit by hand; edit the config or the content and
// re-run `npx tsx scripts/build-nav.ts`.
//
// This seed copy was written by hand on 2026-09-29 so the web package compiles
// before the generator exists. The generator must emit exactly this shape.

export type VersionStatus = 'current' | 'legacy' | 'upcoming'

export interface CategoryInfo {
  id: string
  name: string
  description: string
  icon: string
  articleCount: number
  displayOrder: number
}

export interface SectionInfo {
  id: string
  name: string
  description: string
  icon: string
  displayOrder: number
  categories: CategoryInfo[]
}

export interface VersionInfo {
  id: string
  name: string
  releaseDate: string
  status: VersionStatus
  description: string
  sections: SectionInfo[]
}

export const GAME = 'pz'

export const DEFAULT_VERSION = 'build-41'

export const VERSIONS: VersionInfo[] = [
  {
    id: 'build-41',
    name: 'Build 41',
    releaseDate: '2021-12-20',
    status: 'legacy',
    description:
      'The previous stable build. Guides here are kept as written and are not updated for Build 42.',
    sections: [
      {
        id: 'modding',
        name: 'Modding',
        description: 'Learn to create mods for Project Zomboid',
        icon: 'plug',
        displayOrder: 1,
        categories: [],
      },
      {
        id: 'mapping',
        name: 'Mapping',
        description: 'Create custom maps with TileZed and WorldEd',
        icon: 'map',
        displayOrder: 2,
        categories: [],
      },
    ],
  },
  {
    id: 'build-42',
    name: 'Build 42',
    releaseDate: '2026-07-29',
    status: 'current',
    description:
      'The current stable build (42.20 and later). Modding, mapping, vehicles and the Outcast mods.',
    sections: [],
  },
]

export function getVersion(id: string | undefined): VersionInfo | undefined {
  return VERSIONS.find((v) => v.id === id)
}

export function getSection(versionId: string | undefined, sectionId: string | undefined): SectionInfo | undefined {
  return getVersion(versionId)?.sections.find((s) => s.id === sectionId)
}
